name: Automatic Build
on:
    push:

jobs:
    tests:
        uses: ./.github/workflows/reusable_tests.yml
        secrets: inherit
    
    build:
        uses: ./.github/workflows/reusable_build.yml
        permissions: 
            packages: write
        secrets: inherit