name: Automatic Build
on:
    push:
        branches: 
            - main

jobs:
    tests:
        uses: ./.github/workflows/reusable_tests.yml
        secrets: inherit
    
    build:
        needs: [tests]
        uses: ./.github/workflows/reusable_build.yml
        permissions: 
            packages: write
        secrets: inherit