name: Manual Deploy
on:
    workflow_dispatch:
        #TODO
            
jobs:
    build:
        uses: ./.github/workflows/reusable_build.yml
        permissions: 
            packages: write
        secrets: inherit

    deploy:
        needs: [build]
        uses: ./.github/workflows/reusable_deploy.yml
        permissions:
            packages: write
        with:
            digest: ${{ needs.build.outputs.digest }}
