name: Build
on:
    workflow_call:
        inputs:
            image:
                description: "Name for image build"
                default: devops-demo
                type: string
            registry:
                description: "Image registry"
                type: string
                required: false
        outputs:
            digest:
                description: "Build image digest"
                value: ${{ jobs.build.outputs.digest }}
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.build.outputs.image }}
            digest: ${{ steps.push.outputs.digest }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set variables
              id: variables
              run: |
                echo "date=`date +%Y-%m-%d`" >> $GITHUB_OUTPUT
                ref="${{ github.ref_name }}"
                echo "ref_normalized=${ref//\//-}" >> $GITHUB_OUTPUT
            
            - name: Buildah Build
              id: build
              uses: redhat-actions/buildah-build@v2
              with:
                containerfiles: Containerfile
                image: ${{ inputs.image }}
                tags: >
                    ${{ github.ref_type == 'tag' && github.ref_name || '' }}
                    ${{ github.ref_type == 'branch' && format('{0}-{1}', steps.variables.outputs.ref_normalized , steps.variables.outputs.date) || '' }}
                    ${{ github.ref_name == 'main' && 'latest' || '' }}
                oci: true

            
            - name: Push To Registry
              id: push
              uses: redhat-actions/push-to-registry@v2
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                image: ${{ inputs.image }}
                registry: >
                    ghcr.io/${{ github.repository_owner }}
                tags: >
                    ${{ github.ref_type == 'tag' && github.ref_name || '' }}
                    ${{ github.ref_type == 'branch' && format('{0}-{1}', steps.variables.outputs.ref_normalized , steps.variables.outputs.date) || '' }}
                    ${{ github.ref_name == 'main' && 'latest' || '' }}