name: Sync GitOps
on:
    workflow_call:

env:
  GITOPS_BRANCH: apps/${{ github.event.repository.name }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                repository: paulorpdl/devops-demo-gitops
                ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
            
            - uses: webfactory/ssh-agent@v0.9.1
              name: Add GitOps SSH Key 
              with:
                ssh-private-key: ${{ secrets.GITOPS_SSH_KEY }}

            - name: Checkout to app branch
              run: | 
                git fetch origin $GITOPS_BRANCH || true
                git checkout -B $GITOPS_BRANCH origin/$GITOPS_BRANCH || git checkout -B $GITOPS_BRANCH 

            - name: Download a Build Artifact
              uses: actions/download-artifact@v4.3.0
              with:
                name: manifest.yaml
                path: ./apps/kind-cluster/
            
            - name: Commit and push to GitOps Repo
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add . 
                git commit -am "Updating ${{ github.event.repository.name }} deployment "
                git push origin $GITOPS_BRANCH
                

        