name: Build
on:
    workflow_call:
        inputs:
            image:
                description: "Image Name"
                default: devops-demo
                type: string
            digest:
                description: "Image Digest for Manifests"
                type: string


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: asdf-vm/actions/install@v4

            - name: Prepare deploy manifest
              working-directory: kubernetes/release
              run: | 
                kustomize edit set image \
                ${{ inputs.image }}=ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}@${{ inputs.digest}}

            - name: Kustomization Build
              working-directory: kubernetes
              run: | 
                kustomize build release > ${{ github.event.repository.name }}.yaml

            - uses: actions/upload-artifact@v4
              with:
                path: kubernetes/
                name: kubernetes

            - uses: actions/upload-artifact@v4
              with:
                path: kubernetes/${{ github.event.repository.name }}.yaml
                name: manifest.yaml
                compression-level: 0

            - name: Podman Login
              uses: redhat-actions/podman-login@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: ghcr.io/${{ github.repository_owner }}

            - name: Push manifests to OCR
              run: |
                flux push artifact oci://ghcr.io/${{ github.repository_owner }}/manifests/${{ github.event.repository.name}}:latest \
                  --path="." \
                  --source="$(git config --get remote.origin.url)" \
                  --revision="$(git rev-parse --short HEAD)"
              